### ISSUE TITLE
ANDROID 

### ISSUE THREAD

**Issue by smartypejohn** [gdomenici/plugin.video.pcloud-video-streaming#1]
Great add on mate.  Works perfect on all of my WINDOWS based devices;  however, I keep receiving an error message on my ANDROID devices (ERROR: PCLOUD STREAMING ERROR.   CHECK THE CHANGE LOG FOR MORE INFORMATION ).  I am unable to log in with my credentials;  Once I launch the add on I receive this error message immediately.   Hopefully you'll be able to resolve this issue; I really like this add on and find it very useful for KODI but I need it to work on ANDROID.  THANKS in advance.

**Comment by gdomenici** [comment]
Thanks for bug report @smartypejohn . In fact it looks like the Python interpreter in Android has some quirks compared to the Windows one. I fixed a couple of things to make the Android interpreter happy, but more corner cases keep popping up. Will keep hammering.

**Comment by smartypejohn** [comment]
Thanks I really appreciate your response and I hope this could be
resolved.  Again, great work.

**Comment by smartypejohn** [comment]
I'm sure if this add on is functional for KODI on ANDROID OS devices it will surely gain popularity quick amongst community users.  I can't wait; most of my mobile devices are ANDROID.  Hope all works out mate.   Really appreciate this.  👍

**Comment by gdomenici** [comment]
Thanks for the kind words @smartypejohn . In fact the fixes were pretty easy after all. I have tested it on exactly 1 device (a Motorola Moto G 1st gen with Android 5.1) and at least it works well there now.

I have published release 1.2.0 at https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases; will submit to main Kodi repo soon.

Closing the issue for now, but do feel free to reopen if you still see quirky behavior. If so, kindly specify Android device model and OS version.

Best,

Guido

**Comment by smartypejohn** [comment]
You are the best!!!  Nice!!  I really appreciate your time and work.  This
will definitely be put to good use.  Myb4 year old can now access his
training vids from our pcloud account.   Great!!!  Thumbs up.  If you have
any links or Google wallet account;  I'll be glad to send a donation.
Thanks again.

**Comment by gdomenici** [comment]
Very gracious of you, but a donation won't be necessary. Your enthusiasm is already a reward, and I really mean that. Glad to hear I could help!

Guido

**Comment by smartypejohn** [comment]
Have a happy holiday.  Thanks again.  👍✊
