### ISSUE TITLE
Suggestion: Publish addon on kodi official repository

### ISSUE THREAD

**Issue by Danieldiazi** [gdomenici/plugin.video.pcloud-video-streaming#12]
Hi, great job and useful addon.
This is a suggestion, if it's possible, why not publish your addon on kodi official repository. Kodi users will have the addon in a easy way for download.

Maybe is a hard work, if I can help, no problem!

**Comment by gdomenici** [comment]
Hi @Danieldiazi 
Thanks for the kind words. The plugin is on the official repo already -- it's just a few versions behind the one I publish as a ZIP on the forum. See https://github.com/xbmc/repo-plugins/tree/helix/plugin.video.pcloud-video-streaming.

Kind regards,

Guido
