### ISSUE TITLE
Support for external subtitles

### ISSUE THREAD

**Issue by ehmcruz** [gdomenici/plugin.video.pcloud-video-streaming#13]
Hey. Do you think you can add support for external subtitles?
For instance, it could check if there is a srt subtitle with the same file name as the video file in the pcloud folder, and automatically download the srt file and load  it with the video, as it already happens when the files are local.

**Comment by gdomenici** [comment]
Hi @ehmcruz ,

This is fixed in 1.2.9, available from the releases tab.

Kind regards,

Guido
