### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by benben2033** [gdomenici/plugin.video.pcloud-video-streaming#15]
Hi,
can you add support for case when I have u2f authentification enabled on my pCloud - would be great

**Comment by gdomenici** [comment]
Hi @benben2033 ,

Sure, I'll look into whether that is possible.

Kind regards,

Guido

**Comment by gdomenici** [comment]
Hi @benben2033 

I have contacted PCloud technical support and, alas, they said "Unfortunately, you can't enable the two-factor authentication via the API at this time". And the plugin does need to operate via their API. Sorry about that.

I'll have to close this one, but I'll keep monitoring if the API situation in PCloud changes.

Kind regards,

Guido
