### ISSUE TITLE
PCLOUD STREAMING PLUGIN FOR KODI 16.0 JARVIS

### ISSUE THREAD

**Issue by smartypejohn** [gdomenici/plugin.video.pcloud-video-streaming#2]
Good Evening Guido,

Hope all is well and you and your loved ones are in the best of health.  We spoke before the close of last year in regards to this wonderful add on you developed.  It has been working like a charm for my wife and kids.  As I am sure you are aware; KODI is now at version 16.0 JARVIS and it seems as though the PCLOUD plugin is not as accurate as usual when content is added to my pcloud.  Maybe it requires an update for ANDROID & WINDOWS?  Not sure but I wanted to give you a heads up.  Again, thanks a million for your hard work; it's greatly appreciated over here and if you ever need a donation ; I'l be glad to extend what I can.  

Respectfully,

John Smart

**Comment by gdomenici** [comment]
Hi John,

Thanks again for your kind words. Indeed there was an issue with expired authentication tokens, which would crash the plugin on startup. Now, should that happen, the plugin will show the "authenticate to PCloud" dialog and let the user log on. Tested on Windows and Android, and it seems to work fine. I'll close this; feel free to reopen if version 1.2.3 does not seem to fix the issue.

Kind regards,

Guido

**Comment by smartypejohn** [comment]
Thanks mate.  Is there a link for 1.2.3?  👍😊

**Comment by gdomenici** [comment]
Sure. Just download the ZIP from https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.2.3. You ought to be able to install it with Kodi's "install from zip". I'll also submit it to the official repo, but it usually takes a few days before it's pulled.
