### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

### ISSUE THREAD

**Issue by harryberlin** [gdomenici/plugin.video.pcloud-video-streaming#20]
ssl issue exist any more :(
finally today i did the test for #18 with new version on windows and got the errors again.

`12:23:35.432 T:7240   ERROR: ERROR: cannot logon to pCloud: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
12:23:35.474 T:3432   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.pcloud-video-streaming/?content_type=video
12:23:35.482 T:3432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pcloud-video-streaming/?content_type=video) failed`

**Comment by gdomenici** [comment]
Hi @harryberlin 

Did you do the steps mentioned in #18? Namely,

> set the environment variable PYTHONHTTPSVERIFY=0 in Windows "Advanced system settings" dialog, and launch Kodi after that. If now any Python plugin (not just mine) accesses an HTTPS website with a "bad" TLS certificate, the plugin will ignore the error and proceed as though it was a trusted cert.

Screenshot on Win10:
![Screenshot on Win10](https://i.imgur.com/kVL1T3f.png)

If I do this and _then_ launch Kodi, all cert errors are ignored.

**Comment by harryberlin** [comment]
because of your post in #18 and #19, i thought it is not the method to prefer.

**Comment by gdomenici** [comment]
Hi,

In #18 I fixed the problem with the "+" in the username. The TLS untrusted cert is a different problem which is not related to this plugin as far as I can tell -- in fact, the fact  that the PCloud TLS cert is seen as untrusted on your machine is puzzling to me (it is trusted on all the devices I could lay my hands on).

Yet, with the PYTHONHTTPSVERIFY environment variable, you get a "free" solution to this problem.

**Comment by harryberlin** [comment]
ok

**Comment by kavita9742** [comment]
But i am facing same issue . i have window 10

**Comment by kavita9742** [comment]
still i am facing same issue even though i have set system variable to PYTHONHTTPSVERIFY=0.

**Comment by gdomenici** [comment]
> 
> 
> still i am facing same issue even though i have set system variable to PYTHONHTTPSVERIFY=0.

Hi @kavita9742 

May I have from you a snippet from the relevant lines in the log file? Let me know if you need help finding the log file location.

Kind regards,

Guido

**Comment by gdomenici** [comment]
Closing due to long inactivity. If any need, please reopen.
