### ISSUE TITLE
Plugin version 1.3.1 does not work on Android or on Mac

### ISSUE THREAD

**Issue by gdomenici** [gdomenici/plugin.video.pcloud-video-streaming#23]
See https://forum.kodi.tv/showthread.php?tid=239955&pid=2903428#pid2903428:

> since the last pcloud add-on update on 24-11-19 [version 1.3.1] i cannot stream videos from my account. I use kodi on my android tv, i have 2 different boxes and it doesn't work on either of them. It also doesn't work on my mac.

**Comment by iamratso** [comment]
first device name MIBOX4 XIAOMI
android version 8.1.0
android security patch level may 5 2019
kernel version 4.9.61

second device element smp9003 pro
android version 4.4.2
kernel version ubuntu@ubuntu#2

thank you that's all i can muster i'm a borderline moron with computers

**Comment by gdomenici** [comment]
Thanks for the extra info @iamratso . The issue is (I think) fixed in 1.3.2, which i just published here on GitHub & submitted to the main Kodi plugin repo. I expect that in the next day or two the updated version will show up in the Kodi plugin gallery.

**Comment by iamratso** [comment]
many thanks
