### ISSUE TITLE
Sort by Date

### ISSUE THREAD

**Issue by usphil** [gdomenici/plugin.video.pcloud-video-streaming#24]
Hi, 

I used this addon for a long time and very appreciate your work. It's really help me to watch my video from Kodi and PCLOUD.

I just have a little bit problem with the files sort by name. Will this addon support sort by date option? Now it has the feature sort by name only. It's hard for me to find a new video just added.

Thank you very much for the great addon

**Comment by gdomenici** [comment]
Hi @usphil ,

Thanks for your kind words. Yes, it should be possible. I'll look into it when I find a chunk of time.

Bets regards,

Guido

**Comment by gdomenici** [comment]
(note to self: see http://mirrors.xbmc.org/docs/python-docs/stable/xbmcplugin.html)

**Comment by gdomenici** [comment]
Hi @usphil 

This is now addressed in 1.4.0 (see Releases). In the next day or two it will probably also show up in the official Kodi repo.

Kind regards,

Guido
