### ISSUE TITLE
Feature Request NOT an Issue

### ISSUE THREAD

**Issue by rene1980** [gdomenici/plugin.video.pcloud-video-streaming#26]
Please it is possible, to the following feature
At the Moment it is not possible to access to the Crypto Folder on pCloud
But it would be great if you can add this feature to the pcloud video addon beacause so I (an other useres) can put privat videos to crypto folder and show this over kodi

**Comment by gdomenici** [comment]
Hi @rene1980 ,

Sure, I'll look into whether it is at least possible, as soon as I get a moment. If so, it should not be a problem.

Kind regards,

Guido

**Comment by gdomenici** [comment]
Hi @rene1980 ,

The PCloud documentation does not contain any information on how to use Crypto folders, so I reached out to PCloud support. They say that, alas, the client-side Crypto folders implementation is a "trade secret" if you will, i.e. only possible from their proprietary client software.

I strongly disagree with that position - security should not be done "through obscurity" -- but unfortunately they seem to stand firm on that. So I'm afraid that, until PCloud opens up the client-side implementation, there's nothing I can do.

I'm closing this ticket for now, but will be happy to revisit if something changes on the PCloud side.

Kind regards,

Guido
