### ISSUE TITLE
pCloud Streaming Add On Error Check Log Information Message

### ISSUE THREAD

**Issue by smartypejohn** [gdomenici/plugin.video.pcloud-video-streaming#3]
Good Evening Guido, 

Hope all is well as always.   I think I sent a message last year this time.   Lol;  anyway,  I just wanted to let you know that it seems like the pCloud add on is broken again.   My wife and I continue to use it for the kids and it's a saver!   I would like to thank you again and hope that you could get this plugin back up and running.   Two thumbs up from my 5 year old.... Lol.   Talk soon. 

John Smart

**Comment by smartypejohn** [comment]
KODI Jarvis /Krypton
Android & Windows

**Comment by gdomenici** [comment]
Hi John,

Glad to hear you're still enjoying the plug-in... 

I'll be happy to help, but it works well for me on Kodi 16.1, both on Windows and on Android. 

Maybe an option would be to delete the directory %appdata%\Kodi\userdata\addon_data\plugin.video.pcloud-video-streaming? (on Windows) If you do so, you will be reauthenticated next time you start the plugin, but it lets you start afresh.

If you're still experiencing problems after that:

1. Can you log on to PCloud normally via the web interface?
1. If so, would you like to describe what the exact symptoms are on Kodi?
1. Attaching the contents of the Kodi log file would also be helpful.

Guido

**Comment by smartypejohn** [comment]
Thanks for the response.   It appeared to be some traffic issue directly
associated with pCloud service. I should have let you know sooner but I
didn't pin point the issue until I received a response from pCloud support.
Thank you so much once again for making sure my family and I are
connected.   Lol. Enjoy your weekend. ✊😊
