### ISSUE TITLE
Can't install from zip file

### ISSUE THREAD

**Issue by Theblueearth** [gdomenici/plugin.video.pcloud-video-streaming#34]
When trying to install from zip on Kodi v19 an error shows up saying "The dependency on xbmc.python version 2.19.0 could not be satisfied."

**Comment by gdomenici** [comment]
Hi @Theblueearth ,

This ought to have been fixed by 1.5.0 -- please see https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.5.0.

Kind regards,

Guido
