### ISSUE TITLE
Fixes done for Kodi Matrix

### ISSUE THREAD

**Issue by carneal4** [gdomenici/plugin.video.pcloud-video-streaming#35]
[plugin.video.pcloud-video-streaming-master.zip](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/files/6446063/plugin.video.pcloud-video-streaming-master.zip)

Made updates for compatibility with Kodi Matrix.  Tested and works okay with Mac and Chrome OS.

File listing shows video clips less than 30 seconds.  Maybe someone else can provide a fix?

**Comment by gdomenici** [comment]
Thanks @carneal4 . I have worked in your changes into release 1.5.0 -- see https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.5.0. Thanks for your help.

Will soon submit the plugin to the master repo, too.

Kind regards,

Guido

**Comment by carneal4** [comment]
Guido,

Thanks for coding the original work.  Hope everyone enjoys the updated compatibility with Kodi.

Robert
