### ISSUE TITLE
Kodi Matrix

### ISSUE THREAD

**Issue by gkapan** [gdomenici/plugin.video.pcloud-video-streaming#36]
Hello Guido,

Please help us, kodi matrix is much faster and we need an update for pcloud addon :)

**Comment by gdomenici** [comment]
Hi @gkapan ,

Absolutely. Will look into it as soon as possible.

**Comment by gkapan** [comment]
@gdomenici, this is perfect ! Keep in mind that I have already tested @carneal4 fix in issue #35 and it works in Matrix !!!

https://github.com/gdomenici/plugin.video.pcloud-video-streaming/issues/35

**Comment by gdomenici** [comment]
Hi @gkapan ,

I have massaged in Carneal's changes -- now released 1.5.0. Please see https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/tag/1.5.0.

Soon submitting to master plugins repo.

Kind regards,

Guido
