### ISSUE TITLE
Problem to stream movie from pCloud

### ISSUE THREAD

**Issue by emileleusis** [gdomenici/plugin.video.pcloud-video-streaming#4]
Hello Guido,

I was very happy to find your pcloud plugin for KODI. I'm using Kodi 17 sideloaded to the Fire TV Stick. I can login to the pcloud just fine and see all the content. But as soon as I want to stream an error message pops up telling me that there is a streaming error. I tried to stream the standard mp4 video from the pcloud video folder or mkvs but it always fails. Do you have an idea what might be wrong? 

Thank you for this wonderful plugin.
bye
Udo

**Comment by gdomenici** [comment]
Hi Udo,

Thanks for your kind words. Alas I have a hard time reproducing the issue coz I don't have access to a Fire TV stick at the moment, and otherwise it works OK for me on Windows and on Android.

Do you have any way to get the Kodi log off of the Fire TV Stick and paste it/attach it here? I am not sure if you have direct filesystem access on the Stick, but there is at least one Kodi plugin called "log viewer" (under Programs) that should allow you to at least _view_ the log.

Kind regards,

Guido

**Comment by emileleusis** [comment]
Hello Guido,

thank you for your answer. I tried to make some photos :-( hope the quality
is alright. Seems that there is a problem with the ID that is not
numerical. But you will know better. I got a TV box where I experienced the
same behaviour.
Are the screenshots enough ?
Thank you for your help.

have a pleasant evening.

bye
Udo

2017-03-01 23:06 GMT+01:00 Guido Domenici <notifications@github.com>:

**Comment by gdomenici** [comment]
Hi @emileleusis ,

Thanks for the logs; they do shed light on the issue. I fixed it in 1.2.6. You can download the new version from https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/download/1.2.6/plugin.video.pcloud-video-streaming_1.2.6.zip, or simply wait until it's pulled in the main repo (usually it's a matter of days).

Kind regards,

Guido

**Comment by emileleusis** [comment]
Hello Guido,

wow .... that was fast ! That you so much for your quick help. I tested it
yesterday and it worked like a charme. Thank you for this great plugin.

Have a good weekend.
bye
Udo


Am 03.03.2017 00:00 schrieb "Guido Domenici" <notifications@github.com>:

**Comment by gdomenici** [comment]
You're very welcome. Glad it works out. BTW, I had some trouble with the pull request to the official repo, so it's probably gonna be a while more before it shows up as an automatic update via Kodi.

Kind regards,

Guido
