### ISSUE TITLE
Update README to clarify that the plugin works only when 2FA is disabled on PCloud

### ISSUE THREAD

**Issue by gdomenici** [gdomenici/plugin.video.pcloud-video-streaming#43]
See https://github.com/gdomenici/plugin.video.pcloud-video-streaming/issues/32#issuecomment-763414931

**Comment by Timbo104** [comment]
I intend to write to pCloud in support of your request for PCloud to expose their API to third-party developers. If other Kodi/pCloud users do as well we might be able to apply sufficient pressure to get the developers to do something.

**Comment by gdomenici** [comment]
Thanks for that @Timbo104 . 
OK if I close this ticket in the meantime? It's not like there's anything actionable until PCloud implements this (if they ever do).

**Comment by Timbo104** [comment]
Guido,
I've written to pCloud. They didn't know what Kodi was! I've written a fuller briefing and waiting to hear back from them. I'm not optimistic.
Close the ticket and when I hear something I'll update you.
TimboC

**Comment by gdomenici** [comment]
Thanks @Timbo104 . Closing.
