### ISSUE TITLE
New data region login error

### ISSUE THREAD

**Issue by iamratso** [gdomenici/plugin.video.pcloud-video-streaming#46]
Hello. I have used your excellent addon to stream videos and music from kodi for several years. I just changed the data region of my account from the USA to Europe and I get a login error when I try to log in to my account with the addon. I tried logging in with another account that's in the USA and the login was successful. So the addon must be incompatible with the european servers of pcloud. Could you see if you could remedy that because I would hate to lose the option to stream videos from kodi. Bear in mind that most new pcloud subscribers choose the EU servers for their accounts.
I use kodi leia with version 1.4.2 and matrix with version 1.5.1 and it doesnt work in either case.
Thank you in advance for your time.
Kind regards

**Comment by iamratso** [comment]
I forgot to say that I use android and mac and it doesnt work on either any more.
Thanks again

**Comment by gdomenici** [comment]
Hi @iamratso 

There is a new settings under the addon's setting menu, that lets you choose the data region - US or EU. It defaults to the US one (endpoint https://api.pcloud.com/), but you can switch it there to the EU one (endpoint https://eapi.pcloud.com/).

Hopefully that will fix the issue?

Kind regards,

Guido

**Comment by iamratso** [comment]
Thank you kindly for your swift reply. Does this apply to both 1.4.2 and 1.5.1 versions?
Thanks again.

**Comment by gdomenici** [comment]
Hi,

You're very welcome. 1.5.1 is OK, but in the 1.4.x series you need 1.4.3. See https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases.

Kind regards,

Guido

**Comment by iamratso** [comment]
Hello. I tried it and it works fine. Thank you very much for your help.
Kind regards
