### ISSUE TITLE
Flac streaming

### ISSUE THREAD

**Issue by mash1k** [gdomenici/plugin.video.pcloud-video-streaming#6]
Hello,

great add-on.
I would like to use it to stream flac music files that I have on pcloud. I'm using the android version of kodi on my mobile phone with your plugin.

It works in the current version but only for one file at a time.

Could you please program the add-on to play the next file in the album/folder automatically? and also add next track or previous track buttons...
Is the flac transoded to lower quality  when streaming ? 

Thank you !
Mashik Coller

**Comment by gdomenici** [comment]
Hi @mash1k 

Sure. I'll look into whether it can be done.

Kind regards,

Guido

**Comment by mash1k** [comment]
Thank you! Great work!
This will be better than the official pcloud Android app which plays flac
files only until the middle of the song... I wrote to them about it.

**Comment by gdomenici** [comment]
Hi @mash1k 

Thanks for your kind words.

Turns out there's already a built-in way to "program the add-on to play the next file in the album/folder automatically" -- see https://forum.kodi.tv/showthread.php?tid=213730&pid=1881783#pid1881783. You just need to right-click (desktop) or long-tap (mobile) the first FLAC file you want to play, and select "Play from Here". That will do the trick.

As for the next track/previous track buttons, sorry, but I don't know how to do that...

Best regards,

Guido

**Comment by mash1k** [comment]
Hello, thank you for answering. I tried the play from here button, but it
never goes to next song.. Just stops playing the music.

Also tried in player settings to activate 'play next file automatically'
but didn't work.

Hope you can fix it somehow.

Best regards,
Mashik

On Jun 14, 2017 01:31, "Guido Domenici" <notifications@github.com> wrote:

Hi @mash1k <https://github.com/mash1k>

Thanks for your kind words.

Turns out there's already a built-in way to "program the add-on to play the
next file in the album/folder automatically" -- see https://forum.kodi.tv/
showthread.php?tid=213730&pid=1881783#pid1881783. You just need to
right-click (desktop) or long-tap (mobile) the first FLAC file you want to
play, and select "Play from Here". That will do the trick.

As for the next track/previous track buttons, sorry, but I don't know how
to do that...

Best regards,

Guido

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gdomenici/plugin.video.pcloud-video-streaming/issues/6#issuecomment-308267548>,
or mute the thread

**Comment by mash1k** [comment]
Hello,

Now the 'play from here' option is working !

Thank you,
Mashik

**Comment by gdomenici** [comment]
Hi @mash1k 

Great to hear & sorry for the silence... i really didnt know how to answer, so I'm glad it's working for you now :)

Kind regards,

Guido
