### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by ehmcruz** [gdomenici/plugin.video.pcloud-video-streaming#7]
Great plugin!

I would like to suggest some features:

1- support for loading external subtitles. I have several files with srt subtitles. It would be interesting to be able to load them together with the video, like kodi does when the file is stored locally.

2- sort the files in the folders alfabetically

thx!

**Comment by gdomenici** [comment]
Hi @ehmcruz 

Sorry for the extremely delayed reply!

About 1: yes, I think it can be done. In your view, how would the plugin determine the subtitle filename automatically? Maybe it should look for a file with the same name as the movie file but with an .srt extension, in the same PCloud folder?

About 2: If I'm not mistaken, they're alphabetical already. Please double-check. If not, please provide an example where they're NOT alphabetical and I'll take a look.

Kind regards,

Guido

**Comment by gdomenici** [comment]
Fixed in [version 1.2.7](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases/download/1.2.7/plugin.video.pcloud-video-streaming_1.2.7.zip).
