### ISSUE TITLE
Kodi 17.5 - pCloud 1.2.5 - Unplayable item

### ISSUE THREAD

**Issue by Danieldiazi** [gdomenici/plugin.video.pcloud-video-streaming#8]
Hi
After I've installed pCloud addon from kodi repository (version 1.2.5) on Raspberrry Pi 3 (libreelec with Kodi 17.5) I can't play any file from pCloud (including sample files of pCloud, like pCloud.mp4 or momentum.mp3).

At log viewer I can see:

"ERROR: Playlist player: skipping unplayable item: 0, path
[plugin://plugin.video.pcloud-video-streaming/?mode=file&fileID=4224397089L]
->End of Python script error report <--
ValueError: invalid literal for int() with base 10: '4224397089L'
.....
ValueError: invalid 

"

Thanks in advance for your help

**Comment by gdomenici** [comment]
Hi @Danieldiazi 

I believe I fixed this in version 1.26, which however (for boring reasons) is not in the official Kodi repo yet. If you want, you can install 1.2.6 manually from https://forum.kodi.tv/showthread.php?tid=239955.

Let me know if that doesn't help your issue. In the meantime, I should get off my butt and try and figure out the boring issue that prevents me from updating the plugin in the main repo.

Kind regards,

Guido

**Comment by Danieldiazi** [comment]
Thanks, It works!

**Comment by gdomenici** [comment]
You're welcome! And thanks for the pull request. Merged.

Kind regards,

Guido
